---
- name: copy bash files
  copy:
    src: "{{ item }}"
    dest: "{{  ansible_facts.user_dir }}/.{{ item }}"
    backup: yes
  loop:
    - aliases
    - bash_profile
    - bash_prompt
    - bashrc
    - exports
    - functions