---
- name: install tmux
  yum:
    name: tmux
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'

- name: install tmux
  homebrew:
    name: tmux
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: copy tmux.conf
  copy:
    src: tmux.conf
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    backup: yes
