---
- name: install tmux
  yum:
    name: tmux
    state: present
  become: yes
  when:
    - ansible_facts.os_family == 'RedHat'
    - not ansible_facts.pkg_mgr == 'atomic_container'

- name: install tmux
  command: rpm-ostree install --idempotent tmux
  become: yes
  when:
    - ansible_facts.os_family == 'RedHat'
    - ansible_facts.pkg_mgr == 'atomic_container'

- name: install tmux
  homebrew:
    name: tmux
    state: latest
  when: ansible_facts.distribution == 'MacOSX'

- name: copy tmux.conf
  copy:
    src: tmux.conf
    dest: "{{ ansible_facts.user_dir }}/.tmux.conf"
    backup: yes
