---
- name: install vim on rhel/fedora
  yum:
    name: vim
    state: installed
  when: ansible_os_family == 'RedHat'
  become: yes

- name: install vim on macosx
  homebrew:
    name: vim
    state: present
  when: ansible_distribution == 'MacOSX'

- name: add plugin dirs
  file:
    name: "{{ ansible_user_dir }}/.vim/{{ item }}"
    state: directory
  loop:
    - autoload
    - bundle

- name: install pathogen
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: "{{ ansible_user_dir }}/.vim/autoload/pathogen.vim"

- name: install git plugins
  git:
    repo: "{{ item}}"
    dest: "{{ ansible_user_dir }}/.vim/bundle/{{ (item|basename)[:-4] }}"
    depth: 1
  loop: "{{ git_plugins }}"

- name: copy vimrc
  copy:
    src: vimrc
    dest: "{{ ansible_user_dir }}/.vimrc"
    mode: 0664


